name: release
on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release_linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.25"

      - name: Install just
        uses: taiki-e/install-action@just

      - name: Build for Linux
        run: |
          version=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          just build_release_linux $version

      - name: Add Checksums
        run: |
          cd ./dist
          for file in kanata-tray*; do shasum -a 256 "$file"; done > sha256sums

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          draft: false
          prerelease: false
          files: |
            ./dist/kanata-tray-linux
            LICENSE
            ./dist/sha256sums
